### ISSUE TITLE
Code review - Return Pos() == 0 when declarator doesn't exist (e.g. an unnamed bitfield).

### ISSUE THREAD

**Issue by cznic** [cznic/c#11]
Cf. commit https://github.com/cznic/c/commit/968fa43aad1bd4073987a6e5decdf97ba16e1161

The commit changes `ast.go`, but that's a generated file.

@xlab Please let me know the motivation for this change, ie. in what situation the `.Pos()` method is called on nil receiver. Thank you.

**Comment by xlab** [comment]
Sorry, didn't notice that was `ast.go`.
E.g.: an unnamed bitfield

```C
#if __DARWIN_UNIX03
#define _STRUCT_FP_CONTROL	struct __darwin_fp_control
_STRUCT_FP_CONTROL
{
    unsigned short		__invalid	:1,
    				__denorm	:1,
				__zdiv		:1,
				__ovrfl		:1,
				__undfl		:1,
				__precis	:1,
						:2, // ta-daaa!
				__pc		:2,

..cont'd..
```

**Comment by cznic** [comment]
Parsing

```C
struct s
{
    unsigned short      __invalid   :1,
                    __denorm    :1,
                __zdiv      :1,
                __ovrfl     :1,
                __undfl     :1,
                __precis    :1,
                        :2, // ta-daaa!
                __pc        :2,

};
```

Works just fine.

----

Note: `StructDeclarator` is

```
StructDeclarator:
        Declarator
|       DeclaratorOpt ':' ConstantExpression  // Case 1
```

Ie. a bitfield does not have a `Declarator`, it has a `DeclaratorOpt` instead and `DeclaratorOpt.Pos()` already has the properly generated [test for nil](https://github.com/cznic/c/blob/3f66303b631e0b027441dd77110580b65089eb48/internal/cc/ast.go#L580):

```go
// Pos reports the position of the first component of n or zero if it's empty.
func (n *DeclaratorOpt) Pos() token.Pos {
	if n == nil {
		return 0
	}

	return n.Declarator.Pos()
}
```

Please check if your code calls `Pos()` of the correct entity when `StructDeclarator.Case` is 1.

**Comment by xlab** [comment]
My use case is this:
```Go
	members, _ := typ.Members()
	for _, m := range members {
		log.Println(m.Declarator.Pos())
	}
```

There's a comment in `etc.go` I didn't see the first time:

```C
{
	// skipped
	Declarator   *Declarator // Possibly nil for bit fields.
	// skipped
}
```

Thanks for the clarification! I fixed my code.

**Comment by xlab** [comment]
P.S. no need to review rollbacks if they've been discussed.

**Comment by cznic** [comment]
Okay ;-)
