### ISSUE TITLE
Code review - Add a missing case in `(*cc.Model).value()`, may have more.

### ISSUE THREAD

**Issue by cznic** [cznic/c#12]
Cf. commit https://github.com/cznic/c/commit/9b011c69b5fade00599f9a97967a8b0f6c87c598

@xlab Please let me know the motivation for this change. IINM, `int` (Go type) should never be passed as the `v` parameter of `Model.value`. Where it is coming from and why?

**Comment by xlab** [comment]
Btw, can't remember the specific case now, but this change had a reason when I did it to the fork, there was a panic. I'll remove this patch from my code and check whether the bug reappears somewhere.

**Comment by cznic** [comment]
@xlab PTAL.
