### ISSUE TITLE
TranslationUnit.ConstDefines: Identifier position needed.

### ISSUE THREAD

**Issue by cznic** [cznic/c#14]
@xlab I propose a breaking change as in subject. I would like to change the `ConstDefines` map type to `map[xc.Token]interface{}`. The reason is that in `ccgo` I would like to filter the `#define`s according to their origin.

Thoughts?

**Comment by xlab** [comment]
I'll welcome any changes that expand functionality, even if it's a breaking change.
So `map[xc.Token]interface{}` seems to be more verbose and I like it.

**Comment by xlab** [comment]
However I had in my implementation `type DefinesMap map[string][]xc.Token` which serves the same purpose, i.e. you can filter macros based on their origin. I also want to note that `interface{}` may seem confusing here, better to wrap it into some type.

Frankly, the comment `// Ident ID -> value of #define Ident const-expression.` which seemed clear to me now looks confusing :(

**Comment by cznic** [comment]
OK, another idea: I'll keep `ConstDefines` as they are, no breaking change. I'll just add `ConstDefinesPos`, a `map[int]token.Pos` that'll record the positions of the macro defining token.

Wrt `ConstDefines` type - `map[int]interface{}`. Each `#define` is evaluated as an constant expression, if possible. The resulting value can be of many different types, eg. int, uint, long int, long long int, etc. But also it can be float, double, long double. It can be also a compile time constant pointer to a string, or long string literal. In all those cases, a corresponding Go type, as defined by the `cc.Model`, is returned. In case of string literals, it is `cc.StringLitID` or `cc.LongStringLitID`.

`#define`s of type `#define foo` are returned as bool value true.

I'm open to suggestions. We can introduce some concrete interface type which can describe the const define value. So far, a type switch worked for me well, see for example (WIP): https://github.com/cznic/c/blob/fe2cd7186618852111c885743bada3bdfcfdf264/internal/ccgo/ccgo.go#L217

**Comment by xlab** [comment]
> I'm open to suggestions. We can introduce some concrete interface type which can describe the const define value.

Ok, seems that I need to observe more usage cases in order to suggest any strict interface for this. Type switch is a handy thing too, I'll think about it.

**Comment by cznic** [comment]
> Feel free to close this.

@xlab No hurry ;-)

Please review branch `issus14` (note the typo in the name). It exports all macros as a `map[int]*Macro`. `Macro` has method `ReplacementTokens` which gives you the `[]xc.Token` result you are using in your fork.

Note: The `Macro.Value` field now contains complete garbage, but that is #15 and will be addressed later.

**Comment by xlab** [comment]
> Please review branch issus14 (note the typo in the name).

CC-regarding fixes look good. I assume the name of macro should be fetched via `DefTok` field.

**Comment by cznic** [comment]
> CC-regarding fixes look good.

Thanks for taking a look. I'll merge branch `issus14` now.

> I assume the name of macro should be fetched via DefTok field.

Yes. Additionally the same name ID is available while ranging `TranslationUnit.Macros` keys.

**Comment by cznic** [comment]
Merged.
