### ISSUE TITLE
Separate CC out from C

### ISSUE THREAD

**Issue by xlab** [cznic/c#16]
Hi Jan, I decided to throw away my forked branch and integrate CC directly as it became stable and featureful. However, the problem is that the repo got quite large from the last time I checked, its size grew from `7MB` to `24MB` which is painful for user experience. Also the Go conventions disallow me from using CC out from the `internal/` dir.

My idea is to separate CC out so it'll become `cznic/cc` and I'll be happy to integrate directly. The `c` or `sqlite` projects are rather become a target for integrations later, but CC is a good thing to use.

What do you think? Are you going to do this?
Cheers.

**Comment by cznic** [comment]
Okay, will do it.

**Comment by cznic** [comment]
[Done](https://github.com/cznic/cc) ;-)
