### ISSUE TITLE
Cannot parse macro as a macro function argument

### ISSUE THREAD

**Issue by xlab** [cznic/c#3]
This failed at parse:
```
#define FOO 3

void foo(int a, int b);

#define do_foo(x) \
  foo(x, FOO)
```

Not my idea to do this, but some real world libs use this.

```
main.go:16: error: foo.h:6:3: expected one of [$end, _Bool, _Complex, auto, char, const, double, enum, extern, float, inline, int, long, register, restrict, short, signed, static, struct, typedef, typedefname, union, unsigned, void, volatile]
exit status 1
```

https://github.com/cznic/c/tree/trunk/issues/b_macro_as_macro_func_arg

**Comment by cznic** [comment]
@xlab 

Cannot reproduce with the test just added - please review. Alternatively, can you please provide a self contained compilable reproduction case?

**Comment by xlab** [comment]
For sure, there is a dir with self-containing compilable reproduction cases in `trunk` branch.
This one is in https://github.com/cznic/c/tree/trunk/issues/b_macro_as_macro_func_arg

**Comment by cznic** [comment]
My bad, sorry. I wrongly thought the link provided refers to this issue - I tend to read faster than I should. Thanks for the repro case, will have a look at it right now.
