### ISSUE TITLE
Parse error in legit macro, weird consequence

### ISSUE THREAD

**Issue by xlab** [cznic/c#8]
Not sure what's going on, I was forced to strip ~10 .h files to get this few of lines, plus getting this typedef by following the chain of `sys/*.h` includes.

```C
#define __signed signed

typedef __signed char __int8_t;

// for future tests
// (on the real code this producting another error)
// #if 5 > 1
// // ok?
// #endif

// remove/change this block -> works!
#if !defined(A) && (!defined(B) || defined(C))
// ok?
#endif

#define FOO (4)

// remove this block -> works!
#if (FOO) > 4
// ok?
#endif
```

The code looks legit, however it triggers an error:

```
main.go:16: error: foo.h:16:14: expected one of [!=, $end, %=, &&, &=, '%', '&', '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '[', ']', '^', '|', '}', *=, ++, +=, --, -=, ->, /=, <<, <<=, <=, ==, >=, >>, >>=, ^=, |=, ||]
```

**There are two problems:**
1) parser error itself;
2) the error message which points to the wrong problem (try to remove or change blocks that are marked); the problem will dissolve.

https://github.com/cznic/c/tree/trunk/issues/b_define_wtf

**Comment by cznic** [comment]
FTR, problem narrowed to:

```
dbg lexer.go:376: []xc.Token{ // len 5
· 0: testdata/issue8.h:19:5: '(',
· 1: testdata/issue8.h:19:6: IDENTIFIER "FOO",
· 2: testdata/issue8.h:19:9: ')',
· 3: testdata/issue8.h:19:11: '>',
· 4: testdata/issue8.h:19:13: INTCONST "4",
},
```

incorrectly expands into

```
dbg lexer.go:380: []xc.Token{ // len 7
· 0: testdata/issue8.h:19:5: '(',
· 1: testdata/issue8.h:16:13: '(',
· 2: testdata/issue8.h:16:14: INTCONST "4",
· 3: testdata/issue8.h:16:15: ')',
· 4: testdata/issue8.h:16:14: INTCONST "4",
· 5: testdata/issue8.h:16:15: ')',
· 6: testdata/issue8.h:16:14: INTCONST "4",
} 
```

**Comment by cznic** [comment]
@xlab 

Please review fix at https://github.com/cznic/c/commit/7d616177329a58bcd58a652eee9f30658a7dd17c.

**Comment by xlab** [comment]
@cznic 

Wow, this works! I was able to successfully parse libvpx.

**Comment by cznic** [comment]
Glad to hear that!

It sounds like this CL has got your LGTM. Your "turn" is now: Please merge the `issue8` branch into `master`, delete the `issue8` branch, push all the changes to `origin` and close this issue, thank you ;-)

**Comment by cznic** [comment]
FTR: I did not manually closed the issue, it was closed automatically when you merged the commit with the "magic" commit message - thank you.
