### ISSUE TITLE
(*cc.ctype).Kind() misses a case in "matrioshka"-like typedefs

### ISSUE THREAD

**Issue by xlab** [cznic/c#9]
This code is from `jpeglib.h`

```C
typedef short JBLOCK[64];
typedef JBLOCK *JBLOCKROW;
typedef JBLOCKROW *JBLOCKARRAY;
typedef JBLOCKARRAY *JBLOCKIMAGE;
```

Fails at introspection phase when I'm trying to unpack Ptr/Array types to their core type.

**Packed types:**

```
main.go:22: original:  typedef short[64] Array
main.go:22: original: JBLOCK short(*)[64] Ptr
main.go:22: original: JBLOCKROW short(*(**)[64])[64] Ptr
main.go:22: original: JBLOCKARRAY short(*(**(*(***)[64])[64])[64])[64] Ptr
```

**While unpacking:**

```
go run main.go
main.go:22: original:  typedef short[64] Array
main.go:24: unpacked:  typedef short Short
main.go:22: original: JBLOCK short(*)[64] Ptr
main.go:24: unpacked: JBLOCK short Short
main.go:22: original: JBLOCKROW short(*(**)[64])[64] Ptr
panic: 1

goroutine 1 [running]:
github.com/cznic/c/internal/cc.(*ctype).Kind(0xc820013450, 0x4204f8)
	github.com/cznic/c/internal/cc/etc.go:676 +0x14a
main.unpackType(0x4204f8, 0xc820013450, 0x0, 0x0)
	/issues/b_kind_missing_case/main.go:33 +0x80
main.main()
	/issues/b_kind_missing_case/main.go:23 +0x5ce
exit status 2
make: *** [all] Error 1
```

https://github.com/cznic/c/tree/trunk/issues/b_kind_missing_case

**Comment by cznic** [comment]
@xlab Finally got to look into this issue. Hmm, I have to refresh my C skills first to even figure out what those nested typedefs should actually mean.

**Comment by xlab** [comment]
@cznic yay, the most blocking bug :)

> what those nested typedefs should actually mean.

It seems to me the intention was to create a multi-dimensional data structure.

**Comment by cznic** [comment]
@xlab Please **double** check the fix and its output, as I'm far from sure if the [result `exp` value](https://github.com/cznic/c/commit/202b464e55c3fa0e3f7c54daeb9ee96c976b374e#diff-dd8b2a4c50111a883b077810322e5d3bR915) is what you need and/or expect.

Thank you.

**Comment by xlab** [comment]
@cznic 

Whoa, this is a change! I noticed that nested typedefs are no longer being expanded to the root.
For example, I have this:
```
typedef int32_t MyInt;
```

From now on, `MyInt` is now typed as `cc.TypedefName`, that's it — an opaque type, not resolved to the `int`.
As an end user of the CC API, I need to process further expansions by myself, like I did before when CC was at the early stage. By the way, this seems wrong to me: the CC should be able to expand the type to the original type.

Let me know what's your opinion on this behaviour. Because there is no way back: I've already deleted all the code that made guesses about types when they're opaque, if I add it back, I don't want to delete i again. And will look like a hack-job in any way.

**Comment by xlab** [comment]
As for the case of this issue, `JBLOCKARRAY` should be actually `***short[64]`, 
`JBLOCKROW` as `**short[64]` and so on. I see no troubles making it that way. Isn't this preferable?

**Comment by cznic** [comment]
@xlab 

> Whoa, this is a change! I noticed that nested typedefs are no longer being expanded to the root.

No worries, I will change it to expand the typedefs again as well.

> As for the case of this issue, JBLOCKARRAY should actually be ***short[64]

I'll have to check again if `***short[64]` is a compatible type wrt `typedef JBLOCKROW *JBLOCKARRAY;`

> Let me know what's your opinion on this behaviour. Because there is no way back: I've already deleted all the code that made guesses about types when they're opaque, if I'd add it back, I don't want to delete i again. And it will look like a hack-job in any way.

We will resolve the issue in a way that makes you happy, I promise ;-) Seriously, it's important for me to have the CC API such that cgogen can consume it comfortably. I'm glad the API is not yet public and it can be changed painlessly. I appreciate your feedback very much!

-

Stay tuned, the fix is coming in few hours, I believe.

**Comment by cznic** [comment]
@xlab Typedefs are once again expanded, PTAL.

> As for the case of this issue, JBLOCKARRAY should actually be ***short[64]

GCC seems to disagree:

```bash
(11:44) jnml@r550:~/src/github.com/cznic/c/internal/cc$ cat testdata/issue9b.c 
typedef short JBLOCK[64];
typedef JBLOCK *JBLOCKROW;
typedef JBLOCKROW *JBLOCKARRAY;
typedef JBLOCKARRAY *JBLOCKIMAGE;

short (**ok)[64];
JBLOCKARRAY ok;

short ***bad[64];
JBLOCKARRAY bad;
(11:45) jnml@r550:~/src/github.com/cznic/c/internal/cc$ gcc -o /dev/null testdata/issue9b.c 
testdata/issue9b.c:10:13: error: conflicting types for ‘bad’
testdata/issue9b.c:9:10: note: previous declaration of ‘bad’ was here
(11:45) jnml@r550:~/src/github.com/cznic/c/internal/cc$ 
```

CC seems to agree with GCC:
```bash
(11:45) jnml@r550:~/src/github.com/cznic/c/internal/cc$ go test -run Parse1 -1 testdata/issue9b.c 
--- FAIL: TestParse1 (0.00s)
	all_test.go:769: testdata/issue9b.c:10:13: conflicting types for bad 'short(**)[64]' with external linkage, previous declaration at testdata/issue9b.c:9:7 'short***[64]'
		
FAIL
exit status 1
FAIL	github.com/cznic/c/internal/cc	0.007s
(11:46) jnml@r550:~/src/github.com/cznic/c/internal/cc$ 
```

**Comment by cznic** [comment]
@xlab 

> As an end user of the CC API, I need to process further expansions by myself, like I did before when CC was at the early stage. By the way, this seems wrong to me: the CC should be able to expand the type to the original type.

Also, please confirm that this is no longer a problem, ie. can cgogen now consume the type information w/o expanding it by itself?

**Comment by xlab** [comment]
Ok, that was my bad, I actually meant `JBLOCKIMAGE`, the top most type in this case, which is of type `JBLOCKARRAY *`. 

```
1.c:10:13: error: redefinition of 'bad' with a different type: 'JBLOCKIMAGE' (aka 'short (***)[64]') vs 'short ***[64]'
JBLOCKIMAGE bad;
```

And once again, according to [http://cdecl.org](http://cdecl.ridiculousfish.com/?q=short+***bad%5B64%5D%3B), the type `***short[64]` seems to be

> declare bad as array 64 of pointer to pointer to pointer to short

But actually this should be "pointer to pointer to pointer to array 64 of short" aka `short (***)[64]`.

**Comment by cznic** [comment]
Which program generated this output?

> ```
.c:10:13: error: redefinition of 'bad' with a different type: 'JBLOCKIMAGE' (aka 'short (***)[64]') vs 'short ***[64]'
JBLOCKIMAGE bad;
            ^
1.c:9:10: note: previous definition is here
short ***bad[64];
```

I'm curious because it shows the "typeinfo string" in the same way as CC does. Is it some other version of GCC, perhaps?

**Comment by xlab** [comment]
@cznic That's clang from OS X

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

P.S. at first check the CC works fine now, I got my types expanded. I'll inform you a bit later if I was able to distinguish `short ***[64]` from `short (***)[64]` using the CC API.

**Comment by cznic** [comment]
@xlab Assuming issue fixed. Please feel free to fill another issue if not. Thank you.

**Comment by xlab** [comment]
I finally have found some time to adjust my code to support inner arrays. It works as expected, yay.

```
// Jblock type as declared in jpeg-6b/jpeglib.h:70
type Jblock [64]int16

// Jblockrow type as declared in jpeg-6b/jpeglib.h:71
type Jblockrow [][64]int16

// Jblockarray type as declared in jpeg-6b/jpeglib.h:72
type Jblockarray [][][64]int16

// Jblockimage type as declared in jpeg-6b/jpeglib.h:73
type Jblockimage [][][][64]int16
```

**Comment by cznic** [comment]
:+1: ;-)
